# Generated by Django 5.0.1 on 2024-01-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='purpose_of_visit',
            field=models.CharField(max_length=255),
        ),
    ]
