# Generated by Django 5.0.1 on 2024-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitor_host_alter_visitor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='drive_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='number_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
