# Generated by Django 5.0.1 on 2024-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_visitor_drive_in_visitor_number_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
