# Generated by Django 5.0.1 on 2024-01-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_visitor_tag_number_visitor_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitortag',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
