# Generated by Django 5.0.1 on 2024-01-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_visitor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
