# Generated by Django 5.0.1 on 2024-01-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_visitor_checked_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.visitortag'),
        ),
    ]
