# Generated by Django 5.0.1 on 2024-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_visitor_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitortag',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
