# Generated by Django 5.0.1 on 2024-01-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_visitortag_allocated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.visitortag'),
        ),
    ]
