# Generated by Django 5.0.1 on 2024-01-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_visitor_otp_alter_visitor_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitortag',
            old_name='allocated_at',
            new_name='last_allocated_at',
        ),
    ]
