# Generated by Django 5.0.1 on 2024-01-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_allocated_at_visitortag_last_allocated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitortag',
            name='last_allocated_at',
        ),
        migrations.AddField(
            model_name='visitortag',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
