# Generated by Django 5.0.1 on 2024-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_visitortag_last_allocated_at_visitortag_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitortag',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
