# Generated by Django 5.0.1 on 2024-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_visitortag_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
