# Generated by Django 5.0.1 on 2024-02-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_visitingpurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='purpose_of_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.visitingpurpose'),
        ),
    ]
